Add `no_std` support to `wgpu-types` (#6892)
* Initial Commit

* Remove now-redundant `format` import

* Update CHANGELOG.md

* Appropriately feature-gate `texture_format_serialize` test

* Remove `alloc` feature

Also fixed some documentation links and a Wasm `std` import

* Revert change to `Serialize` for `TextureFormat`

* Combine use statements

* Switch from `PathBuf` to `String`

* Consider environmental flags as unset on `no_std`

* Fix missing `format!`

* Add new CI tasks for `no_std` testing

* Comment out known failing CI matrix option

* Update all usage of `Dx12Compiler::DynamicDxc`

* Added comments to CI

* Update .github/workflows/ci.yml

* Update .github/workflows/ci.yml

* Update .github/workflows/ci.yml

* CI Touchups

---------

Co-authored-by: Connor Fitzgerald <connorwadefitzgerald@gmail.com>

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -91,29 +91,34 @@ jobs:
           - name: Windows x86_64
             os: windows-2022
             target: x86_64-pc-windows-msvc
+            tier: 1
             kind: native
 
           # Windows
           - name: Windows aarch64
             os: windows-2022
             target: aarch64-pc-windows-msvc
+            tier: 2
             kind: native
 
           # MacOS
           - name: MacOS x86_64
             os: macos-14
             target: x86_64-apple-darwin
+            tier: 1
             kind: native
 
           - name: MacOS aarch64
             os: macos-14
             target: aarch64-apple-darwin
+            tier: 1
             kind: native
 
           # IOS
           - name: IOS aarch64
             os: macos-14
             target: aarch64-apple-ios
+            tier: 2
             kind: native
 
           # VisionOS
@@ -121,36 +126,58 @@ jobs:
             os: macos-14
             target: aarch64-apple-visionos
             kind: wgpu-only
-            toolchain: nightly
+            tier: 3
             extra-flags: -Zbuild-std
 
           # Linux
           - name: Linux x86_64
             os: ubuntu-22.04
             target: x86_64-unknown-linux-gnu
+            tier: 1
             kind: native
 
           - name: Linux aarch64
             os: ubuntu-22.04
             target: aarch64-unknown-linux-gnu
+            tier: 1
             kind: native
 
           # Android
           - name: Android aarch64
             os: ubuntu-22.04
             target: aarch64-linux-android
+            tier: 2
             kind: native
 
           # WebGPU/WebGL
           - name: WebAssembly
             os: ubuntu-22.04
             target: wasm32-unknown-unknown
+            tier: 2
             kind: web
 
           - name: Emscripten
             os: ubuntu-22.04
             target: wasm32-unknown-emscripten
+            tier: 2
             kind: wgpu-only
+          
+          # TODO: Uncomment once web-sys updates past 0.3.76
+          # See https://github.com/rustwasm/wasm-bindgen/pull/4378 for details
+          # - name: WebAssembly Core 1.0
+          #   os: ubuntu-22.04
+          #   target: wasm32v1-none
+          #   tier: 2
+          #   kind: no_std
+          
+          # Bare-metal x86-64
+          # TODO: Remove once web-sys updates past 0.3.76
+          # Included while wasm32v1-none is failing to ensure `no_std` does not regress
+          - name: no_std x86_64
+            os: ubuntu-22.04
+            target: x86_64-unknown-none
+            tier: 2
+            kind: no_std
 
     name: Clippy ${{ matrix.name }}
     runs-on: ${{ matrix.os }}
@@ -159,8 +186,8 @@ jobs:
       - name: checkout repo
         uses: actions/checkout@v4
 
-      - name: Install Toolchain (Repo MSRV)
-        if: matrix.toolchain != 'nightly'
+      - name: Install Toolchain (Repo MSRV - Tier 1 or 2)
+        if: matrix.tier == 1 || matrix.tier == 2
         run: |
           rustup toolchain install ${{ env.REPO_MSRV }} --no-self-update --profile=minimal --component clippy
           rustup target add ${{ matrix.target }} --toolchain ${{ env.REPO_MSRV }}
@@ -178,8 +205,8 @@ jobs:
       #
       # RUSTC_BOOTSTRAP=1 is how the rust project builds itself when bootstrapping the compiler, so while not "stable"
       # it has been around for many years and don't anticipate it going away any time soon.
-      - name: Install Toolchain (Repo MSRV - Pseudo Nightly)
-        if: matrix.toolchain == 'nightly'
+      - name: Install Toolchain (Repo MSRV - Tier 3)
+        if: matrix.tier == 3
         run: |
           rustup toolchain install ${{ env.REPO_MSRV }} --no-self-update --profile=minimal --component clippy,rust-src
           echo "RUSTC_BOOTSTRAP=1" >> "$GITHUB_ENV"
@@ -246,6 +273,19 @@ jobs:
           # Check with all features.
           cargo clippy --target ${{ matrix.target }} ${{ matrix.extra-flags }} -p wgpu-hal --all-features
           cargo clippy --target ${{ matrix.target }} ${{ matrix.extra-flags }} -p wgpu --all-features
+        
+      # Building for no_std platforms where every feature is enabled except "std".
+      - name: check no_std
+        if: matrix.kind == 'no_std'
+        shell: bash
+        run: |
+          set -e
+
+          # check with no features
+          cargo clippy --target ${{ matrix.target }} ${{ matrix.extra-flags }} -p wgpu-types --no-default-features
+
+          # Check with all features except "std".
+          cargo clippy --target ${{ matrix.target }} ${{ matrix.extra-flags }} -p wgpu-types --no-default-features --features strict_asserts,fragile-send-sync-non-atomic-wasm,serde,counters
 
       # Building for native platforms with standard tests.
       - name: check native
